#!/bin/bash -l


#########################################################################################
# SLURM job script
##########################################################################################

# queue
#SBATCH -p cpu2

# jobname
#SBATCH -J Jobname

# User notify on events (begin,end,fail,requeue,all)
#SBATCH --mail-type=all
#SBATCH --mail-user=MUN_EMAIL

# redirect output to file
#SBATCH --output job-%j.out
#SBATCH --error job-%j.err

# number of nodes (16 cores per node) = a
#SBATCH --nodes=1

# Specify number of mpi tasks (total) = b
#SBATCH --ntasks=1

# Specify number of OpenMP threads per MPI task = c
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --time=03:30:00
# load environment
start=$SECONDS
maxduration=11400
module add gromacs/2020.1/gnu_gpu
module load python/2.7.11

export GMX_MAXBACKUP=-1
#export GMX_GPU_ID=` echo ${CUDA_VISIBLE_DEVICES} | sed "s/\|,//g" `
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}

gmx grompp -f eq.mdp -o eq.tpr -c equilibrated.gro -n index.ndx -p topol.top -maxwarn -1

PROGRAM="gmx"
PROGRAM_OPTIONS="mdrun -dlb yes -cpi -deffnm eq"

TASKSET_OPTIONS=`cat /tmp/TASKSET_OPTIONS_${SLURM_JOB_ID}`

set

echo "srun `which $PROGRAM` $PROGRAM_OPTIONS"
srun --mpi=pmi2 `which $PROGRAM` $PROGRAM_OPTIONS

gmx grompp -f prod.mdp -o prod.tpr -c eq.gro -n index.ndx -p topol.top -maxwarn -1


PROGRAM="gmx"
PROGRAM_OPTIONS="mdrun -dlb yes -cpi -deffnm prod"

TASKSET_OPTIONS=`cat /tmp/TASKSET_OPTIONS_${SLURM_JOB_ID}`

set

echo "srun `which $PROGRAM` $PROGRAM_OPTIONS"
srun --mpi=pmi2 `which $PROGRAM` $PROGRAM_OPTIONS & pid=$!

echo "pid" ${pid} "with round" $i 
flag=0
while true; do
	ps cax | grep ${pid}  > /dev/null
	if [ $? -ne 0 ]; then
		echo "process" ${pid} "gone for iteration step " ${i}
		break
	fi

	duration=$(( SECONDS - start ))
	
	
	if [ "$duration" -ge "$maxduration" ]; then
		echo "max duration reached for while on step " ${i} ",pid " ${pid}
		kill ${pid}
		flag=1
		break
   	fi
	sleep 60
	
done

echo "moving to analysis"

module unload gromacs/2020.1/gnu_gpu
rm prod.tpr

module load gromacs/5.1.3/gnu_cpu
gmx grompp -f prod.mdp -o prod.tpr -c eq.gro -n index.ndx -p topol.top -maxwarn -1


python ../analysis_gro.py
#dump frame of the last generated traj
fstep=$(grep -A1 "Step" prod.log | awk '{ print $NF}' | tail -n 1)

fstep2=$(echo "$fstep-20" | bc )
echo 0 | gmx trjconv -f prod.trr -o frame.gro -dump $fstep2 -s prod.tpr -vel

rm centered.xtc
rm *tpr*

# submit: sbatch <this_file_name>
# job state: squeue -u <username>
# queue state: sinfo
# view fair-share-priority: sprio -ll
# delete a job: scancel <jobnumber>
